=== kimcw614-creator/metadata_coffee-project/coffee.xsd
<!--메타데이터론 김채완 XSD-->

<xs:schema
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns="http://example.org/coffee"
xmlns:coffee="http://example.org/coffee"
xmlns:dc="http://purl.org/dc/elements/1.1/"
targetNamespace="http://example.org/coffee"
elementFormDefault="qualified">

<!-- DC import -->
<xs:import 
    namespace="http://purl.org/dc/elements/1.1/"
    schemaLocation="http://dublincore.org/schemas/xmls/simpledc20021212.xsd"/>

<!-- Root Element -->
 <!-- Collection -->
 <xs:element name="collection">
    <xs:annotation>
        <xs:documentation>
            A container for multiple coffee beverage records.
        </xs:documentation>
    </xs:annotation>
 </xs:element>

<!-- 각 커피 음료 하나의 레코드-->
<xs:element name="coffeeRecord">
    <xs:annotation>
        <xs:documentation>
        A record describing a coffee beverage with sensory, origin, and preparation metadata.
        </xs:documentation>
    </xs:annotation>

    <xs:complexType>
        <xs:sequence>

            <!-- 제목 (필수, 1회) -->
            <xs:element ref="dc:title"/>

            <!-- beverageType (필수) -->
            <xs:element name="beverageType" type="coffee:beverageTypeType"/>

            <!-- brewMethod (필수) -->
            <xs:element name="brewMethod" type="coffee:brewMethodType"/>

            <!-- beanOrigin (선택, 반복 가능) -->
            <xs:element name="beanOrigin" type="coffee:beanOriginType" minOccurs="0" maxOccurs="unbounded"/>

            <!-- roastLevel (선택) -->
            <xs:element name="roastLevel" type="coffee:roastLevelType" minOccurs="0"/>

            <!-- flavorProfile (필수, 반복 가능) -->
            <xs:element name="flavorProfile" type="coffee:flavorProfileType" maxOccurs="unbounded"/>

            <!-- acidityLevel (선택) -->
            <xs:element name="acidityLevel" type="coffee:acidityLevelType" minOccurs="0"/>

            <!-- caffeineContent (필수) -->
            <xs:element name="caffeineContent" type="coffee:caffeineType"/>

            <!-- milkBase (선택) -->
            <xs:element name="milkBase" type="coffee:milkBaseType" minOccurs="0"/>

            <!-- sweetenerFlavor (선택, 반복 가능) -->
            <xs:element name="sweetenerFlavor" type="coffee:sweetenerType" minOccurs="0" maxOccurs="unbounded"/>

            <!-- servingFormat (필수) -->
            <xs:element name="servingFormat" type="coffee:servingFormatType"/>

        </xs:sequence>
    </xs:complexType>
</xs:element>

<!-- Controlled Vocabularies -->
<!-- beverageType -->
<xs:simpleType name="beverageTypeType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="espresso-based"/>
        <xs:enumeration value="brewed coffee"/>
        <xs:enumeration value="cold brew"/>
        <xs:enumeration value="ready-to-drink"/>
        <xs:enumeration value="flavored beverage"/>
    </xs:restriction>
</xs:simpleType>

<!-- brewMethod -->
<xs:simpleType name="brewMethodType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="espresso"/>
        <xs:enumeration value="pour-over"/>
        <xs:enumeration value="drip machine"/>
        <xs:enumeration value="French press"/>
        <xs:enumeration value="cold brew"/>
    </xs:restriction>
</xs:simpleType>

<!-- beanOrigin -->
<xs:complexType name="beanOriginType">
        <xs:annotation>
            <xs:documentation>
            Structured origin information of the coffee beans.
            Includes country, region, and optional farm name.
            </xs:documentation>
        </xs:annotation>

     <xs:sequence>
        <!-- 필수 -->
        <xs:element name="country" type="xs:string"/>

        <!-- 선택 -->
        <xs:element name="region" type="xs:string" minOccurs="0"/>
        <xs:element name="farm" type="xs:string" minOccurs="0"/>
    </xs:sequence>
</xs:complexType>

<!-- roastLevel -->
<xs:simpleType name="roastLevelType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="light"/>
        <xs:enumeration value="medium"/>
        <xs:enumeration value="dark"/>
    </xs:restriction>
</xs:simpleType>

<!-- flavorProfile -->
<xs:simpleType name="flavorProfileType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="fruity"/>
        <xs:enumeration value="nutty"/>
        <xs:enumeration value="chocolatey"/>
        <xs:enumeration value="floral"/>
        <xs:enumeration value="smoky"/>
        <xs:enumeration value="citrus"/>
        <xs:enumeration value="caramel"/>
        <xs:enumeration value="spicy"/>
        <xs:enumeration value="sweet"/>
    </xs:restriction>
</xs:simpleType>

<!-- acidityLevel -->
<xs:simpleType name="acidityLevelType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="low"/>
        <xs:enumeration value="medium"/>
        <xs:enumeration value="high"/>
    </xs:restriction>
</xs:simpleType>

<!-- caffeineContent -->
<xs:simpleType name="caffeineType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="caffeinated"/>
        <xs:enumeration value="decaffeinated"/>
    </xs:restriction>
</xs:simpleType>

<!-- milkBase -->
<xs:simpleType name="milkBaseType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="none"/>
        <xs:enumeration value="dairy milk"/>
        <xs:enumeration value="oat milk"/>
        <xs:enumeration value="soy milk"/>
        <xs:enumeration value="almond milk"/>
    </xs:restriction>
</xs:simpleType>

<!-- sweetenerFlavor -->
<xs:simpleType name="sweetenerType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="none"/>
        <xs:enumeration value="sugar"/>
        <xs:enumeration value="vanilla"/>
        <xs:enumeration value="caramel"/>
        <xs:enumeration value="hazelnut"/>
        <xs:enumeration value="mocha"/>
    </xs:restriction>
</xs:simpleType>

<!-- servingFormat -->
<xs:simpleType name="servingFormatType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="hot"/>
        <xs:enumeration value="iced"/>
        <xs:enumeration value="bottled"/>
        <xs:enumeration value="canned"/>
        <xs:enumeration value="takeaway"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== kimcw614-creator/metadata_coffee-project/coffee records example_김채완.xml
<?xml version="1.0" encoding="UTF-8"?>

<coffee:collection
xmlns="http://example.org/coffee"
xmlns:coffee="http://example.org/coffee"
xmlns:dc="http://purl.org/dc/elements/1.1/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://example.org/coffee https://raw.githubusercontent.com/kimcw614-creator/metadata_coffee-project/main/coffee.xsd">

<!--예가체프 드립커피 레코드 예시-->
<coffee:coffeeRecord>
    <dc:title>Ethiopia Yirgacheffe Pour-over</dc:title>
    <coffee:beverageType>brewed coffee</coffee:beverageType>
    <coffee:brewMethod>pour-over</coffee:brewMethod>
    <coffee:beanOrigin>
        <coffee:country>Etgiopia</coffee:country>
    </coffee:beanOrigin>
    <coffee:roastLevel>light</coffee:roastLevel>
    <coffee:flavorProfile>floral</coffee:flavorProfile>
    <coffee:flavorProfile>citrus</coffee:flavorProfile>
    <coffee:acidityLevel>high</coffee:acidityLevel>
    <coffee:caffeineContent>caffeinated</coffee:caffeineContent>
    <coffee:milkBase>none</coffee:milkBase>
    <coffee:sweetenerFlavor>none</coffee:sweetenerFlavor>
    <coffee:servingFormat>hot</coffee:servingFormat>
</coffee:coffeeRecord>

<!--RTD 바닐라라떼 레코드 예시-->
<coffee:coffeeRecord>
    <dc:title>Bottled Vanilla Latte</dc:title>
    <coffee:beverageType>ready-to-drink</coffee:beverageType>
    <coffee:brewMethod>espresso</coffee:brewMethod>
    <coffee:beanOrigin>
        <coffee:country>Colombia</coffee:country>
        <coffee:region>Huila</coffee:region>
    </coffee:beanOrigin>
    <coffee:roastLevel>medium</coffee:roastLevel>
    <coffee:flavorProfile>caramel</coffee:flavorProfile>
    <coffee:flavorProfile>sweet</coffee:flavorProfile>
    <coffee:acidityLevel>low</coffee:acidityLevel>
    <coffee:caffeineContent>caffeinated</coffee:caffeineContent>
    <coffee:milkBase>dairy milk</coffee:milkBase>
    <coffee:sweetenerFlavor>vanilla</coffee:sweetenerFlavor>
    <coffee:servingFormat>bottled</coffee:servingFormat>
</coffee:coffeeRecord>

</coffee:collection>
